### ISSUE TITLE
shopify inventory sync

### ISSUE THREAD

**Issue by codecheffy** [secretpizzaparty/shopify-connect-for-woocommerce#28]
Hey there!

Looking to use this plugin for a site I'm making. Just wondering about how or if the inventory syncs.

For example, I sell have 5 shoes in stock. I sell 1 on wordpress site and then i sell one directly through the shopify shop. Will woocommerce count that as 2 sold or just 1?

**Comment by jkudish** [comment]
With this plugin all sales are tracked through Shopify exclusively. The idea is to use WooCommerce to display the productions but have Shopify handle all the sale/inventory/etc logic.

So the answer to your question is neither; WooCommerce doesn't count the sale.
