### ISSUE TITLE
Add to Cart Not working.

### ISSUE THREAD

**Issue by karanzen** [secretpizzaparty/shopify-connect-for-woocommerce#29]
Hello Team,

Here is the link of one of the product: 
http://www.samsung.switch.com.kw/?product=samsung-gear-s3-frontier

It is getting added to default woocommerce cart and not the shopify cart. I guess for some reason the link is not proper. 

Can you please help me out.

**Comment by karanzen** [comment]
Can you please solve it

**Comment by nickhamze** [comment]
The way the app works is it removes the WooCommerce add to cart button and adds the Shopify one instead. The buttons on that page aren't regular WooCommerce buttons (generated by the default WooCommerce functions), so they can't be swapped out with the Shopify one.
